name: Deploy package

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction

      # we run the tests here again, to avoid deployment with failed tests
      - name: Run pytest and coverage
        run: poetry run coverage run --source=secsgem -m pytest tests secsgem --doctest-modules

      - name: Lint with prospector
        run: poetry run prospector --no-autodetect --output-format=pylint secsgem

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.7
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          ignore_dev_requirements: "yes"
